apiVersion: ako.vmware.com/v1alpha1
kind: AviInfraSetting
metadata:
  name: infra-setting-1
spec:
  seGroup:
    name: tkg-cluster-workload-1
  network:
    vipNetworks:
      - networkName: nsx-external-pg
        cidr: 1.1.1.0/24
    enableRhi: true
    bgpPeerLabels:
      - vrf-1
  l7Settings:
    shardSize: MEDIUM
